# Generated by Django 3.1.5 on 2021-01-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_name', models.CharField(default='', max_length=100)),
                ('scenario_name', models.CharField(default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('study_time', models.CharField(default='', max_length=100)),
                ('average_reward', models.IntegerField(default=0)),
                ('status', models.SmallIntegerField(choices=[(0, '学习前'), (1, '学习中'), (2, '已完成'), (3, '学习异常'), (4, '服务中')], default=0)),
                ('env', models.CharField(default='', max_length=100)),
                ('env_config', models.CharField(default='', max_length=100)),
                ('num_gpus', models.IntegerField(default=1)),
                ('num_gpus_per_worker', models.IntegerField(default=1)),
                ('framework', models.SmallIntegerField(choices=[(0, 'torch'), (1, 'tensorflow')], default=0)),
                ('model', models.CharField(default='', max_length=100)),
                ('vf_share_layers', models.BooleanField(default=True)),
                ('vf_loss_coeff', models.FloatField(default=0.0)),
                ('kl_coeff', models.FloatField(default=0.0)),
                ('vf_clip_param', models.FloatField(default=0.0)),
                ('lambda_1', models.FloatField(default=0.0)),
                ('clip_param', models.FloatField(default=0.0)),
                ('lr_min', models.FloatField(default=0.0)),
                ('lr_max', models.FloatField(default=0.0)),
                ('num_sgd_iter', models.IntegerField(default=0)),
                ('sgd_minibatch_size', models.IntegerField(default=0)),
                ('rollout_fragment_length', models.IntegerField(default=0)),
                ('train_batch_size', models.IntegerField(default=0)),
                ('num_workers', models.IntegerField(default=0)),
                ('training_iteration', models.IntegerField(default=0)),
                ('num_samples', models.IntegerField(default=0)),
                ('checkpoint_freq', models.IntegerField(default=0)),
                ('keep_checkpoints_num', models.IntegerField(default=0)),
                ('algorithm', models.SmallIntegerField(choices=[(0, 'PPO')])),
                ('result_storage_path', models.CharField(default='', max_length=200)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
