# Generated by Django 3.1.5 on 2021-01-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='algorithm',
            field=models.SmallIntegerField(choices=[(0, 'PPO')], verbose_name='算法'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='average_reward',
            field=models.IntegerField(default=0, verbose_name='平均奖赏值'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='checkpoint_freq',
            field=models.IntegerField(default=0, verbose_name='模型参数文件保存频率'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='clip_param',
            field=models.FloatField(default=0.0, verbose_name='截断系数'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='env',
            field=models.CharField(default='', max_length=100, verbose_name='环境名称'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='env_config',
            field=models.CharField(default='', max_length=100, verbose_name='环境类配置参数'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='framework',
            field=models.SmallIntegerField(choices=[(0, 'torch'), (1, 'tensorflow')], default=0, verbose_name='深度学习框架'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='keep_checkpoints_num',
            field=models.IntegerField(default=0, verbose_name='保存最近的参数文件个数'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='kl_coeff',
            field=models.FloatField(default=0.0, verbose_name='kl_散度系数'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='lambda_1',
            field=models.FloatField(default=0.0, verbose_name='lambda'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='lr_max',
            field=models.FloatField(default=0.0, verbose_name='学习率上限'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='lr_min',
            field=models.FloatField(default=0.0, verbose_name='学习率下限'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='model',
            field=models.CharField(default='', max_length=100, verbose_name='网络模型配置'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='num_gpus',
            field=models.IntegerField(default=1, verbose_name='GPU个数'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='num_gpus_per_worker',
            field=models.IntegerField(default=1, verbose_name='每个worker的GPU个数'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='num_samples',
            field=models.IntegerField(default=0, verbose_name='实验个数'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='num_sgd_iter',
            field=models.IntegerField(default=0, verbose_name='随机梯度下降迭代次数'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='num_workers',
            field=models.IntegerField(default=0, verbose_name='worker数量'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='result_storage_path',
            field=models.CharField(default='', max_length=200, verbose_name='结果文件路径'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='rollout_fragment_length',
            field=models.IntegerField(default=0, verbose_name='rollout长度'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='scenario_name',
            field=models.CharField(default='', max_length=100, verbose_name='想定名称'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='scene_name',
            field=models.CharField(default='', max_length=100, verbose_name='场景名称'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='sgd_minibatch_size',
            field=models.IntegerField(default=0, verbose_name='随机梯度下降minibatch大小'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '学习前'), (1, '学习中'), (2, '已完成'), (3, '学习异常'), (4, '服务中')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='study_time',
            field=models.CharField(default='', max_length=100, verbose_name='学习时长'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='train_batch_size',
            field=models.IntegerField(default=0, verbose_name='训练batch大小'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='training_iteration',
            field=models.IntegerField(default=0, verbose_name='训练迭代次数'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='vf_clip_param',
            field=models.FloatField(default=0.0, verbose_name='vf_截断参数'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='vf_loss_coeff',
            field=models.FloatField(default=0.0, verbose_name='vf_损失系数'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='vf_share_layers',
            field=models.BooleanField(default=True, verbose_name='价值函数共享层'),
        ),
    ]
