# Generated by Django 3.1.5 on 2021-01-22 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0002_auto_20210122_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scene',
            options={'ordering': ('created',), 'verbose_name': '场景表', 'verbose_name_plural': '场景表'},
        ),
        migrations.AlterModelTable(
            name='scene',
            table='scene',
        ),
    ]
